"""Packaging contract tests: .ffgui association parsing, locator chain, script header."""

import json

from fftui.model import Job

from ffgui.controller import Controller, locate_ffmpeg


def test_ffgui_association_parses_to_job(tmp_path, qapp, monkeypatch):
    """The file the Inno Setup registry entry opens must load into the queue."""
    shell, doc, c, tmp = _wired(qapp, tmp_path, monkeypatch)
    job_file = tmp / "my job.ffgui"
    job_file.write_text(json.dumps({
        "version": 1,
        "job": {"inputs": [{"path": "a.mp4"}], "outputs": [{"path": "o.mp4"}]},
        "meta": {"name": "My job"},
    }), encoding="utf-8")
    c.open_job_file(str(job_file))
    assert doc.items[0].meta["name"] == "My job"
    assert doc.items[0].job.outputs[0].path == "o.mp4"


def test_ffgui_association_rejects_garbage(tmp_path, qapp, monkeypatch):
    shell, doc, c, tmp = _wired(qapp, tmp_path, monkeypatch)
    bad = tmp / "bad.ffgui"
    bad.write_text("{ not json", encoding="utf-8")
    c.open_job_file(str(bad))
    assert not doc.items
    truncated = tmp / "trunc.ffgui"
    truncated.write_text('{"version": 1}', encoding="utf-8")
    c.open_job_file(str(truncated))
    assert not doc.items


def _wired(qapp, tmp_path, monkeypatch):
    from PySide6.QtCore import QSettings

    from fftui.ffmpeg.capability_index import CapabilityIndex

    from ffgui.doc import QueueDocument
    from ffgui.ui.shell import Shell

    monkeypatch.setenv("FFGUI_CACHE_DIR", str(tmp_path / "cache"))
    shell = Shell()
    doc = QueueDocument(CapabilityIndex.stub())
    controller = Controller(shell, doc, CapabilityIndex.stub(),
                            QSettings(str(tmp_path / "s.ini"), QSettings.Format.IniFormat))
    return shell, doc, controller, tmp_path


def test_locator_chain_ffmpeg_path_env_wins(qapp, tmp_path, monkeypatch):
    """Binding order: FFMPEG_PATH → last-good setting → PATH → sibling ffmpeg.exe."""
    from PySide6.QtCore import QSettings

    explicit = tmp_path / "explicit" / "ffmpeg.exe"
    explicit.parent.mkdir()
    explicit.write_bytes(b"")
    remembered = tmp_path / "remembered" / "ffmpeg.exe"
    remembered.parent.mkdir()
    remembered.write_bytes(b"")
    monkeypatch.setenv("FFMPEG_PATH", str(explicit))
    settings = QSettings(str(tmp_path / "s.ini"), QSettings.Format.IniFormat)
    settings.setValue("ffmpeg_path", str(remembered))
    monkeypatch.setattr("ffgui.controller.shutil.which", lambda name: None)
    assert locate_ffmpeg(settings) == (str(explicit), True)

    monkeypatch.delenv("FFMPEG_PATH")
    assert locate_ffmpeg(settings) == (str(remembered), True)


def test_exported_script_carries_provenance_header(qapp, tmp_path, monkeypatch):
    shell, doc, c, tmp = _wired(qapp, tmp_path, monkeypatch)
    from fftui.model import Input, Output

    from ffgui.doc import QueueItem

    doc.items.append(QueueItem(
        Job(inputs=[Input(path="a.mp4")], outputs=[Output(path="o.mp4")]),
        {"name": "x", "enabled": True, "notes": "", "source_hash": ""}))
    out = tmp / "run.bat"
    c.export_to(str(out), "bat")
    text = out.read_bytes().decode("utf-8")
    assert "rem Generated by ffgui" in text
    assert "rem ffmpeg version hash:" in text
    # `rem` comments escape cmd metacharacters (`>` -> `^>`), so no bare `->` remains.
    assert "rem " in text and "-^>" in text


def test_icon_asset_builds(qapp, tmp_path):
    """make_icon.py renders the original artwork to a real .ico."""
    import importlib.util
    from pathlib import Path

    spec = importlib.util.spec_from_file_location(
        "make_icon", Path(__file__).resolve().parents[1] / "build" / "make_icon.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    assert module.main() == 0
    assert (Path(module.__file__).parent / "ffgui.ico").is_file()


def test_version_matches_pyproject():
    """ffgui.__version__ (stamped into exported scripts) must track pyproject."""
    import tomllib
    from pathlib import Path

    import ffgui

    pyproject = tomllib.loads(
        (Path(__file__).resolve().parents[1] / "pyproject.toml").read_text(encoding="utf-8"))
    assert ffgui.__version__ == pyproject["project"]["version"]


def test_build_scripts_track_pyproject_version():
    """nuitka --file-version and Inno AppVersion must drift with pyproject."""
    import re
    import tomllib
    from pathlib import Path

    root = Path(__file__).resolve().parents[1]
    version = tomllib.loads(
        (root / "pyproject.toml").read_text(encoding="utf-8"))["project"]["version"]
    nuitka = (root / "build" / "nuitka.cmd").read_text(encoding="utf-8")
    assert f"--file-version={version}" in nuitka
    iss = (root / "build" / "setup.iss").read_text(encoding="utf-8")
    assert re.search(rf'#define AppVersion "{re.escape(version)}"', iss)


def test_nuitka_script_declares_required_flags():
    text = (__import__("pathlib").Path("build/nuitka.cmd").read_text(encoding="utf-8"))
    for flag in ("--onefile", "--windows-console-mode=disable",
                 "--enable-plugin=pyside6", "--include-data-dir=assets=assets"):
        assert flag in text
