#!/bin/sh
set -e
trap 'printf "Press Enter to close... "; read -r dummy || true' EXIT
# Generated by ffgui 0.1.0 on 2026-09-05 00:00 UTC
# ffmpeg version hash: 0123456789abcdef
# in.mp4 -> o.mkv
cat > 'C:\ffgui-scratch\fftui-chapters-df9d46585dc3bbac.ffmetadata' <<'FFGUI_EOF'
;FFMETADATA1
[CHAPTER]
TIMEBASE=1/1000
START=0
END=0
title=Intro & titles
language=eng
FFGUI_EOF
'C:\ffgui-bin\ffmpeg.EXE' -hide_banner -y -i in.mp4 -i 'C:\ffgui-scratch\fftui-chapters-df9d46585dc3bbac.ffmetadata' -map_chapters 1 o.mkv
