@echo off
setlocal DisableDelayedExpansion
rem Generated by ffgui 0.1.0 on 2026-09-05 00:00 UTC
rem ffmpeg version hash: 0123456789abcdef
rem in.mp4 -^> o.mkv
> C:\ffgui-scratch\fftui-chapters-df9d46585dc3bbac.ffmetadata (
 echo(;FFMETADATA1
 echo([CHAPTER]
 echo(TIMEBASE=1/1000
 echo(START=0
 echo(END=0
 echo(title=Intro ^& titles
 echo(language=eng
)
C:\ffgui-bin\ffmpeg.EXE -hide_banner -y -i in.mp4 -i C:\ffgui-scratch\fftui-chapters-df9d46585dc3bbac.ffmetadata -map_chapters 1 o.mkv
if not %errorlevel%==0 goto ffgui_fail
echo All commands finished.
pause
endlocal & exit /b 0
:ffgui_fail
echo One of the commands failed.
pause
endlocal & exit /b 1
