#!/bin/sh
set -e
trap 'printf "Press Enter to close... "; read -r dummy || true' EXIT
# Generated by ffgui 0.1.0 on 2026-09-05 00:00 UTC
# ffmpeg version hash: 0123456789abcdef
# p1.mp4 (+1 more) -> joined.mp4
mkdir -p 'C:\ffgui-scratch'
cat > 'C:\ffgui-scratch\fftui-concat-a910846eeabe9a05.txt' <<'FFGUI_EOF'
file 'p1.mp4'
file 'p2 & more.mp4'
FFGUI_EOF
'C:\ffgui-bin\ffmpeg.EXE' -hide_banner -y -f concat -safe 0 -i 'C:\ffgui-scratch\fftui-concat-a910846eeabe9a05.txt' -c:v copy -c:a copy joined.mp4
