@echo off
setlocal DisableDelayedExpansion
rem Generated by ffgui 0.1.0 on 2026-09-05 00:00 UTC
rem ffmpeg version hash: 0123456789abcdef
rem p1.mp4 ^(+1 more^) -^> joined.mp4
if not exist C:\ffgui-scratch mkdir C:\ffgui-scratch
> C:\ffgui-scratch\fftui-concat-a910846eeabe9a05.txt (
 echo(file 'p1.mp4'
 echo(file 'p2 ^& more.mp4'
)
C:\ffgui-bin\ffmpeg.EXE -hide_banner -y -f concat -safe 0 -i C:\ffgui-scratch\fftui-concat-a910846eeabe9a05.txt -c:v copy -c:a copy joined.mp4
if not %errorlevel%==0 goto ffgui_fail
echo All commands finished.
pause
endlocal & exit /b 0
:ffgui_fail
echo One of the commands failed.
pause
endlocal & exit /b 1
