#!/bin/sh
set -e
trap 'printf "Press Enter to close... "; read -r dummy || true' EXIT
# Generated by ffgui 0.1.0 on 2026-09-05 00:00 UTC
# ffmpeg version hash: 0123456789abcdef
# clip_100%.mp4 -> done_50%.mp4
'C:\ffgui-bin\ffmpeg.EXE' -hide_banner -y -i clip_100%.mp4 done_50%.mp4
