@echo off
setlocal DisableDelayedExpansion
rem Generated by ffgui 0.1.0 on 2026-09-05 00:00 UTC
rem ffmpeg version hash: 0123456789abcdef
rem my clip ^& ^(cut^).mp4 -^> out put.mp4
C:\ffgui-bin\ffmpeg.EXE -hide_banner -y -i "my clip & (cut).mp4" "out put.mp4"
if not %errorlevel%==0 goto ffgui_fail
echo All commands finished.
pause
endlocal & exit /b 0
:ffgui_fail
echo One of the commands failed.
pause
endlocal & exit /b 1
