#!/bin/sh
set -e
trap 'printf "Press Enter to close... "; read -r dummy || true' EXIT
# Generated by ffgui 0.1.0 on 2026-09-05 00:00 UTC
# ffmpeg version hash: 0123456789abcdef
# in.mp4 -> o.mp4
'C:\ffgui-bin\ffmpeg.EXE' -hide_banner -y -i in.mp4 -c:v libx264 -b:v 500k o.mp4
