#!/bin/sh
set -e
trap 'printf "Press Enter to close... "; read -r dummy || true' EXIT
# Generated by ffgui 0.1.0 on 2026-09-05 00:00 UTC
# ffmpeg version hash: 0123456789abcdef
# видео ファイル.mp4 -> выход.mkv
'C:\ffgui-bin\ffmpeg.EXE' -hide_banner -y -i 'видео ファイル.mp4' -c:v libx264 ' выход.mkv'
