"""Export data model shared by the .bat/.sh serializers."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import PurePosixPath, PureWindowsPath

from fftui.util.command_builder import Sidecar


@dataclass(frozen=True)
class ScriptHeader:
    """Provenance block rendered as comments at the top of every exported script."""

    generator: str
    ffmpeg_version_hash: str
    created_utc: str
    summary: str

    def __post_init__(self) -> None:
        for attr in ("generator", "ffmpeg_version_hash", "created_utc", "summary"):
            if not isinstance(getattr(self, attr), str):
                raise ValueError(
                    f"header {attr} must be a string, "
                    f"got {type(getattr(self, attr)).__name__}")


@dataclass(frozen=True)
class ExportBlock:
    """One ffmpeg invocation plus the generated files its argv refers to."""

    argv: list[str] = field(default_factory=list)
    sidecars: list[Sidecar] = field(default_factory=list)
    workdir_note: str = ""


#: The one script-splice set: a line break or NUL in a token would splice
#: script lines. Every serializer gates on this tuple — never a re-spelled
#: literal. `"` is NOT a member: shlex.quote renders it safely for `.sh`;
#: only cmd.exe cannot quote it, so `.bat` refuses it with its own rule.
HOSTILE_CHARS = ("\n", "\r", "\0")


def contains_hostile(value: str) -> bool:
    """One shared check over the single hostile set."""
    return any(c in value for c in HOSTILE_CHARS)


def reject_hostile(token: str) -> None:
    if not isinstance(token, str):
        raise ValueError(f"token must be a string, got {type(token).__name__}")
    for bad in HOSTILE_CHARS:
        if bad in token:
            raise ValueError(f"token contains {bad!r}: {token!r}")


def sidecar_parent(path: str) -> str:
    parsed = PureWindowsPath(path) if PureWindowsPath(path).drive else PurePosixPath(path)
    return str(parsed.parent)


def prune_repeated_sidecars(blocks: list[ExportBlock]) -> list[ExportBlock]:
    """Drop sidecars an earlier block already embeds: two passes share one
    content-addressed file and one_file queues reuse identical ones, so each
    sidecar is written once, ahead of its first use. Keyed on path AND
    content — same path with different bytes must never collapse."""
    seen: set[tuple[str, str]] = set()
    out: list[ExportBlock] = []
    for block in blocks:
        fresh = [car for car in block.sidecars
                 if (car.path, car.content) not in seen]
        seen.update((car.path, car.content) for car in block.sidecars)
        out.append(block if len(fresh) == len(block.sidecars)
                   else ExportBlock(list(block.argv), fresh, block.workdir_note))
    return out


def header_comment(header: ScriptHeader, prefix: str) -> list[str]:
    gen = " ".join(header.generator.split())
    created = " ".join(header.created_utc.split())
    version = " ".join(header.ffmpeg_version_hash.split())
    summary = " ".join(header.summary.split())
    return [f"{prefix}Generated by {gen} on {created}",
            f"{prefix}ffmpeg version hash: {version}",
            f"{prefix}{summary}"]
